/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihancalculator;
import javax.swing.JOptionPane;

/**
 *
 * @author NEPU
 */
public class FormCalculator extends javax.swing.JFrame {
    Double hasil, bil1, bil2;

    /**
     * Creates new form FormCalculator
     */
    public FormCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbil1 = new javax.swing.JTextField();
        txtbil2 = new javax.swing.JTextField();
        txthasil = new javax.swing.JTextField();
        cmdJumlah = new javax.swing.JButton();
        cmdKurang = new javax.swing.JButton();
        cmdKali = new javax.swing.JButton();
        cmdBagi = new javax.swing.JButton();
        cmdSisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Contoh Kalkulator");

        jLabel2.setText("Bilangan 1");

        jLabel3.setText("Bilangan 2");

        jLabel4.setText("Hasil");

        cmdJumlah.setText("+");
        cmdJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdJumlahActionPerformed(evt);
            }
        });

        cmdKurang.setText("-");
        cmdKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKurangActionPerformed(evt);
            }
        });

        cmdKali.setText("X");
        cmdKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKaliActionPerformed(evt);
            }
        });

        cmdBagi.setText("/");
        cmdBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBagiActionPerformed(evt);
            }
        });

        cmdSisa.setText("SISA BAGI");
        cmdSisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbil1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbil2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmdSisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdKali, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdJumlah)
                    .addComponent(cmdKurang)
                    .addComponent(cmdKali)
                    .addComponent(cmdBagi))
                .addGap(18, 18, 18)
                .addComponent(cmdSisa)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdJumlahActionPerformed
        // TODO add your handling code here:
        hitung(0);
    }//GEN-LAST:event_cmdJumlahActionPerformed

    private void cmdKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKurangActionPerformed
        // TODO add your handling code here:
        hitung(1);
    }//GEN-LAST:event_cmdKurangActionPerformed

    private void cmdKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKaliActionPerformed
        // TODO add your handling code here:
        hitung(2);
    }//GEN-LAST:event_cmdKaliActionPerformed

    private void cmdBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBagiActionPerformed
        // TODO add your handling code here:
        hitung(3);
    }//GEN-LAST:event_cmdBagiActionPerformed

    private void cmdSisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSisaActionPerformed
        // TODO add your handling code here:
        hitung(4);
    }//GEN-LAST:event_cmdSisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCalculator().setVisible(true);
            }
        });
    }
    
    public void hitung(int opsi) {
        // 0 = tambah
        // 1 = kurang
        // 2 = kali
        // 3 = bagi
        // 4 = sisa
        if (txtbil1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Anda belum mengisi bilangan 1");
            txtbil1.requestFocus();
        } else if (txtbil2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Anda belum mengisi bilangan 2");
            txtbil2.requestFocus();
        } else {
            bil1 = Double.parseDouble(txtbil1.getText());
            bil2 = Double.parseDouble(txtbil2.getText());
            
            switch(opsi){
                case 0  : hasil = bil1 + bil2;
                          break;
                case 1  : hasil = bil1 - bil2;
                          break;
                case 2  : hasil = bil1 * bil2;
                          break;
                case 3  : hasil = bil1 / bil2;
                          break;
                case 4  : hasil = bil1 % bil2;
                          break;
            }

            txthasil.setText(""+hasil);

            txtbil1.setText("");
            txtbil2.setText("");
            txtbil1.requestFocus();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBagi;
    private javax.swing.JButton cmdJumlah;
    private javax.swing.JButton cmdKali;
    private javax.swing.JButton cmdKurang;
    private javax.swing.JButton cmdSisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtbil1;
    private javax.swing.JTextField txtbil2;
    private javax.swing.JTextField txthasil;
    // End of variables declaration//GEN-END:variables
}
